---
BbyvRrB002: type//Box
CbyvRrB003: type//Spontaneous::Page
CbyvRrB004: type//Page
DbyvRrB005: field/CbyvRrB004/title
DbyvRrB006: type//Spontaneous::Piece
DbyvRrB007: type//Piece
ztxzBuB002: type//HomePage
AtxzBuB003: layout/ztxzBuB002/home
AtxzBuB004: type//AboutPage
AtxzBuB005: layout/AtxzBuB004/standard
BtxzBuB006: type//ClientsPage
CtxzBuB007: layout/BtxzBuB006/standard
CtxzBuB008: type//ContactPage
CtxzBuB009: layout/CtxzBuB008/standard
CtxzBuB00a: type//CaseStudy
CtxzBuB00b: field/CtxzBuB00a/welcome
CtxzBuB00c: field/CtxzBuB00a/feature_image
CtxzBuB00d: field/CtxzBuB00a/thumb_image
CtxzBuB00e: field/CtxzBuB00a/home_image
CtxzBuB00f: type//Project
DtxzBuB00g: layout/CtxzBuB00f/project
DtxzBuB00h: type//Typeface
DtxzBuB00i: layout/DtxzBuB00h/typeface
EtxzBuB00m: type//ProjectsSection
EtxzBuB00n: box/EtxzBuB00m/case_studies
EtxzBuB00o: layout/EtxzBuB00m/showcase
FtxzBuB00p: type//TypefacesSection
JtxzBuB00q: box/FtxzBuB00p/case_studies
JtxzBuB00r: layout/FtxzBuB00p/showcase
KtxzBuB00s: type//Text
KtxzBuB00t: field/KtxzBuB00s/text
KtxzBuB00u: type//Video
KtxzBuB00v: field/KtxzBuB00u/video
DcbBBuB002: box/ztxzBuB002/sections
5iKBBuB002: box/CbyvRrB004/sections
