---
:development: &defaults
  :adapter:    mysql2
  :database:   julie_com
  :user:       julie
  :password:   


:test:
  <<:         *defaults
  :database:   julie_com_test

:production:
  <<:         *defaults
  :adapter:   mysql2
  :database:  julie_com
  :user:      julie
  :password:  XXX

:rake:
  <<:         *defaults


